Medium.create!(title: 'Starfish', suggested_by: 'Porscha', media_type: 'movie')
Medium.create!(title: 'Alita: Battle Angel', suggested_by: 'Lev', media_type: 'movie')
Medium.create!(title: 'Captain Marvel', suggested_by: 'Kavi', media_type: 'movie')
Medium.create!(title: 'The Burden', suggested_by: 'Joey', media_type: 'movie')
Medium.create!(title: 'Moulin Rouge', suggested_by: 'Marissa', media_type: 'movie')
Medium.create!(title: 'Akira', suggested_by: 'Jide', media_type: 'movie')
Medium.create!(title: 'Ghost in the Shell', suggested_by: 'Jide', media_type: 'movie')
Medium.create!(title: 'Cowboy Bebop', suggested_by: 'Alex', media_type: 'movie')
Medium.create!(title: 'Midsommar', suggested_by: 'Eldred', media_type: 'movie')
Medium.create!(title: 'Us', suggested_by: 'Mars', media_type: 'movie')
