Medium.create!(title: 'Starfish', suggested_by: 'Porscha')
Medium.create!(title: 'Alita: Battle Angel', suggested_by: 'Lev')
Medium.create!(title: 'Captain Marvel', suggested_by: 'Kavi')
Medium.create!(title: 'The Burden', suggested_by: 'Joey')
Medium.create!(title: 'Moulin Rouge', suggested_by: 'Marissa')
Medium.create!(title: 'Akira', suggested_by: 'Jide')
Medium.create!(title: 'Ghost in the Shell', suggested_by: 'Jide')
Medium.create!(title: 'Cowboy Bebop', suggested_by: 'Alex')
Medium.create!(title: 'Midsommar', suggested_by: 'Eldred')
Medium.create!(title: 'Us', suggested_by: 'Mars')
